* TODO Items [0/1]
  - [ ] removeWords not working. wrong argument? trying to
    remove common organizational words

* Background
I implement something like GTD ('getting things done')
personal organization system with EMACS Org mode. I thought
it'd be useful to mine my agenda files for a summary of what
I'm usually up to. Because when asked, I always think,
'well, I dunno - it's in my org files/agenda. I find it hard to put all
of it in accessible memory, if you will. I just execute it.'.

This will work more widely, on any text corpus. But perhaps
I'll author an R package to do some operations on org agenda
files for meaningful text mining after.


* Setup data and readme
  - /data for data (in my case, symlinks to org files)
  - README.rmd

#+begin_src sh
mkdir data
touch analysis.Rmd
#+end_src


* Setup git
  - initialize
  - create remote repo
  - setup gitignore
  - set upstream remote
  - commit and push

#+begin_src sh
echo 'data/*' >> .gitignore
# git remote add origin git@github.com:jo-tham/org_text_miner.git
# git push -u origin master
#+end_src


* Symlink org files
  - symlink to all org files
    - in the future could do all org files on machine
    - even do all org files on machine into the
      corresponding subdirs from root and build the corpus 

#+begin_src sh
ln -s ~/projects/9999-99-99_master/*.org ~/projects/9999-99-99_master_text_miner/data
ls -a ~/projects/9999-99-99_master_text_miner/data
#+end_src

#+RESULTS:
|------------------|
| computing.org    |
| fynanse.org      |
| personal.org     |
| physical.org     |
| reading.org      |
| website.org      |
|------------------|


* References/acknowledgements
  - [[https://gist.github.com/jnrbsn/708961][GPL-3 markdown]]
